### ISSUE TITLE
Deployed app needs to have browserified softap-setup updated

### ISSUE THREAD

**Issue by indraastra** [msolters/softap-setup-meteor#3]
I'm not sure how deploying to meteor.com works exactly, but locally I had to run `meteor reset` first in order to get the softap.browserify.js file to "update" to 3.0.2. 

Since npm support seems to be kind of a hack to begin with, I don't know if the build process is intended to take dependency updates into account, which means this might be a recurring issue.

**Comment by msolters** [comment]
Yes, I've been trying to dig down and find what package is making this decision (not to overwrite).

> FWIW I've used a lot of NPM packages w/ Meteor, and Meteor always rebuilds when the NPM version of a dependency is bumped.

I know that the `cosmos:browserify` package has a cache, wouldn't be surprised if that has something to do with this.  I know it's not in `/packages/npm-container`, so it must be in `/.meteor`, because it affects clones of the repo.

**Comment by msolters** [comment]
But it's definitely working on Safari in Mac!!  I just flashed the new system2.bin to a fresh Photon here, and tried it in El Capitan.

**Comment by msolters** [comment]
Change has propagated to the deployed URL.  Confirmed and working, same as local.

**Comment by msolters** [comment]
No, I'm totally wrong.  Can't be in `/.meteor`.  I'd have seen whatever the change was.

I reason that it must be a local cache (i.e., in our `~` folders).  We both had a copy of the old version -- as did the remote server -- because we had built a previous version.  It's the only explanation that covers the commonality of the issue as well as the response to `meteor reset` or package removal.

**Comment by indraastra** [comment]
One thing that occurs to me is that the files in .meteor/local/build are cached with readonly permissions. Could it be that even if the cosmos-browserify plugin is functioning properly, it wasn't able to overwrite the cached softap.browserify.js?

**Comment by indraastra** [comment]
Nevermind, that's silly. I don't see how anything would update in that case. I'm just glad it's working!

**Comment by msolters** [comment]
![](http://z-nerd.com/wp-content/uploads/2015/06/52311788.jpg)
